---

  - name: "Update APT cache"
    apt: update_cache=yes

  # We are going to install Node via NodeSource repo. @see: https://github.com/nodesource/distributions
  
  - name: Add NodeSource repository key
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present
  
  - name: Add Node binary repository from NodeSource and update apt cache
    apt_repository:
      repo: "deb https://deb.nodesource.com/{{ NODE_VERSION }} {{ ansible_distribution_release }} main"
      update_cache: yes
      state: present

  - name: Add Node src repository from NodeSource and update apt cache
    apt_repository:
      repo: "deb-src https://deb.nodesource.com/{{ NODE_VERSION }} {{ ansible_distribution_release }} main"
      update_cache: yes
      state: present

  - name: Install (or update) Node.js ver. {{ NODE_VERSION }}
    apt:
      name: "nodejs"
      state: latest
      update_cache: yes
      cache_valid_time: 600
    