---
  
  - name: "Update APT cache"
    apt: update_cache=yes

  - name: Install common packages
    apt: name={{ item }} state=present
    with_items:
      - vim
      - wget
      - curl
      - zip
      - unzip      
      - sudo   
    
  - debug: msg="Linux Kernel {{ ansible_kernel }}"
        
  # we only need this for Docker hosts and if Kernel is not already new enough (e.g. 4.x)
  - name: "Update Linux kernel to support layerfs"
    include: add-overlayfs-support.yml
    when: docker_host is defined and ansible_kernel | match("3.\d.*-generic")